// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bixlqmqiorschsjfgcdz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpeGxxbXFpb3JzY2hzamZnY2R6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1ODE5ODYsImV4cCI6MjA2ODE1Nzk4Nn0.ac-JOUJ3xy3QgC76WYYjQi_bOTPnu8gtFxUEeJW3T0Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});